insert into Department([Department Name], Employee) values (1, 1)
insert into Department([Department Name], Employee) values (1, 2)
insert into Department([Department Name], Employee) values (1, 3)
insert into Department([Department Name], Employee) values (2, 6)
insert into Department([Department Name], Employee) values (2, 7)
insert into Department([Department Name], Employee) values (2, 4)
insert into Department([Department Name], Employee) values (3, 5)